---
title: "bark demo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installation

Install from github  (needs C++ compilation)

```{r}
suppressMessages(devtools::install_github("merliseclyde/bark"))
library(bark)
```


### Generate data

```{r}
set.seed(42)
n = 500
circle2 = as.data.frame(sim.Circle(n, dim = 2))

```

```{r, fig.width=4, fig.height=4 }
plot(x.1 ~ x.2, data=circle2, col=y+1)
```

```{r cache=TRUE}
set.seed(42)
train = sample(1:n, size = floor(n/2), rep=FALSE)
circle2.bark = bark(as.matrix(circle2[train, 1:2]), circle2[train, 3], 
                              x.test = as.matrix(circle2[-train, 1:2]),
                    classification = TRUE,
                    type="se")
```

```{r}
#Classify
#
mean((circle2.bark$yhat.test.mean > 0) != circle2[-train, "y"])
```

## SVM

```{r}
library(e1071)
```

```{r}
circle2.svm = svm(y ~ x.1 + x.2, data=circle2[train,], type="C")
pred.svm = predict(circle2.svm, circle2[-train,])
mean(pred.svm != circle2[-train, "y"])
```


```{r}
library(BART)
circle.bart = pbart(x.train = circle2[train, 1:2],  y.train = circle2[train, "y"])
pred.bart = predict(circle.bart, circle2[-train, 1:2])
mean((pred.bart$prob.test.mean > .5) != circle2[-train, "y"])
```

```{r}
par(mfrow=c(1,3))
plot(x.1 ~ x.2, data=circle2[-train,], pch = y+15, col=(1 +( circle2.bark$yhat.test.mean > 0)), main="bark")

plot(x.1 ~ x.2, data=circle2[-train,], pch = y+15, col= as.numeric(pred.svm), main="svm")

plot(x.1 ~ x.2, data=circle2[-train,], pch = y+15, col= ( 1 + (pred.bart$prob.test.mean > .5)), main="BART")

```

